### ISSUE TITLE
cv2 install

### ISSUE THREAD

**Issue by heasungkim** [AiHackathon2018/AI-Vision#100]
![cv2](https://user-images.githubusercontent.com/45214216/50724723-4c25df00-1135-11e9-9324-4ff220a0843a.PNG)
![cv2 1](https://user-images.githubusercontent.com/45214216/50724735-68298080-1135-11e9-89ff-9d252fafe124.PNG)

nsml run -d ir_ph1_v2 -e main.py(baseline code)을 실행하면 cv2 importerror가 에러가 뜹니다.
그래서 pip install opencv-python를 하면 cv2가 이미 설치되었다고 나오는데, 이런 경우 cv2에러를 어떻게 해결해야 할까요?

**Comment by ttagu99** [comment]
local 에 설치해서 발생하는 문제인거 같네요. 저도 nsml 처음 써보긴 합니다만. 만드신 코드 -> nsml 서버로 업로드 -> 실행 되는 시스템 인거 같고,  서버는 정해진 가상 docker가 먼저 실행되고, 업로드된 본인코드가 실행되는 구조 인거 같네요. 정해진 가상 docker 상에 opencv 가 인스톨 안된상태라서 문제가 발생하는것이고, 패키지를 설치하려면, setup.py 에 아래 코드 추가하시면 됩니다.
![image](https://user-images.githubusercontent.com/10820453/50724973-ac1e8480-1139-11e9-8093-caff4305e2e7.png)

**Comment by heasungkim** [comment]
> local 에 설치해서 발생하는 문제인거 같네요. 저도 nsml 처음 써보긴 합니다만. 만드신 코드 -> nsml 서버로 업로드 -> 실행 되는 시스템 인거 같고, 서버는 정해진 가상 docker가 먼저 실행되고, 업로드된 본인코드가 실행되는 구조 인거 같네요. 정해진 가상 docker 상에 opencv 가 인스톨 안된상태라서 문제가 발생하는것이고, 패키지를 설치하려면, setup.py 에 아래 코드 추가하시면 됩니다.
> ![image](https://user-images.githubusercontent.com/10820453/50724973-ac1e8480-1139-11e9-8093-caff4305e2e7.png)

**Comment by heasungkim** [comment]
@ttagu99 
그렇겠네요! 답변 감사합니다! 그럼 cv2에러가 없으신 분들은 다들 setup.py파일 수정하신 건가요..?!
방금 setup.py에 'opencv-python'넣고 nsml run해보았는데, 아래와 같은 새로운 에러가 뜨네요...
![error](https://user-images.githubusercontent.com/45214216/50725065-2996c480-113b-11e9-859f-36e0c4412166.PNG)

**Comment by ttagu99** [comment]
아 이거 저도 확신은 없지만, 몇번 써본 경험으로 말씀드리면. 실제 서버에서 코드가 잘못된건 아닌거 같고. 뭔가 클라이언트-서버간 통신만 끊긴것처럼... 시간이 지나거나, 리프레쉬 해보면 정상돌더라고요. 본인 코드 문제는 아닌거 같습니다.

**Comment by heasungkim** [comment]
제가 뭐 하나를 빠뜨린 거였네요ㅠ 해결했습니다!
