### ISSUE TITLE
nsml submit 하면 internal server error가 발생합니다.

### ISSUE THREAD

**Issue by jireh-father** [AiHackathon2018/AI-Vision#104]
nsml submit 하면 internal server error가 발생합니다.

submit했을때 로그는 확인할 수 없나요?

아래는 submit명령과 에러메세지입니다.

=======================================================
F:\develop\tensorflow-image-retrieval-nsml>nsml submit jireh_family/ir_ph1_v2/21 1
........
Building docker image. It might take for a while
......Error: Submit/infer session is stopped right after running. Please check your code again
time="2019/01/06 04:24:29.677" level=fatal msg="Internal server error"

**Comment by ttagu99** [comment]
흠.. 저도 같은 에러 인데요. 해결하셨나요?
저는 다른세션의 모델을 로딩해서. 새 세션에서 모델 세이브하고, 
infer 함수만 수정했는데 발생했습니다. 혹 공통점이 있나요?

Z:\kaggle\naver_hack\mdw>nsml submit Zonber/ir_ph1_v2/98 0
........
Building docker image. It might take for a while
......Error: Submit/infer session is stopped right after running. Please check your code again
time="2019/01/07 15:39:28.502" level=fatal msg="Internal server error"

**Comment by Hackoperation** [comment]
안녕하세요.
`submit -t`로 디버깅한 결과는 어떻게 되나요?

**Comment by ttagu99** [comment]
> 안녕하세요.
> `submit -t`로 디버깅한 결과는 어떻게 되나요?

결과는 동일합니다.

Z:\kaggle\naver_hack\mdw>nsml submit Zonber/ir_ph1_v2/98 0 -t
........
Building docker image. It might take for a while
......
Session Zonber/ir_ph1_v2/100 is started
Error: Submit/infer session is stopped right after running. Please check your code again
time="2019/01/07 15:44:58.360" level=fatal msg="Internal server error"

**Comment by Hackoperation** [comment]
@ttagu99  

`Zonber/ir_ph1_v2/100 ` 이세션은 entry file이 `no_train.py`인데요, `nsml.save()`를 마지막으로 호출하고 세션이 종료됩니다.

`main.py` 에 있는것처럼 `nsml.paused()` 함수를 호출 해 주셔야합니다.

**Comment by ttagu99** [comment]
> @ttagu99
> 
> `Zonber/ir_ph1_v2/100 ` 이세션은 entry file이 `no_train.py`인데요, `nsml.save()`를 마지막으로 호출하고 세션이 종료됩니다.
> 
> `main.py` 에 있는것처럼 `nsml.paused()` 함수를 호출 해 주셔야합니다.

네 감사합니다. 저는 해결됬습니다
