### ISSUE TITLE
nsml에 외부 모듈 설치 가능한가요?

### ISSUE THREAD

**Issue by DaehunGwak** [AiHackathon2018/AI-Vision#108]
안녕하세요. `24시간이모자라` 팀의 곽대훈입니다.

nsml에 사이킷 런을 설치해서 쓰고 싶은데 아래와 같은 `Permission Denied`가 발생해서 쓰질 못하고있습니다.

혹시 쓸 수 있게하는 방법이 따로 없을까요?

![image](https://user-images.githubusercontent.com/12469427/50732045-b2eadd00-11b5-11e9-991b-7d8565cfbbda.png)

**Comment by deneb2016** [comment]
setup.py 파일에 필요한 패키지를 추가하면 됩니다.

**Comment by DaehunGwak** [comment]
@deneb2016 감사합니다 👍 👍
