### ISSUE TITLE
sklearn사용

### ISSUE THREAD

**Issue by heasungkim** [AiHackathon2018/AI-Vision#110]
안녕하세요.
nsml안에 sklearn module이 설치되어 있지 않는 건가요?! sklearn사용하고 싶은데, 따로 설치해서 사용할 방법이 있는 건지 궁금합니다.

**Comment by deneb2016** [comment]
setup.py 파일에 필요한 패키지를 추가하시면 됩니다.
`setup(
    name='nsml vision hackathon',
    version='1.0',
    description='nsml vision hackathon',
    install_requires=[scikit-learn
    ]
)`

**Comment by nsml-admin** [comment]
https://github.com/AiHackathon2018/AI-Vision/issues/108 
@deneb2016  님이 말씀해주신것처럼 `setup.py` 에 추가해주시면 됩니다.

```python
#nsml: nsml/ml:cuda9.0-cudnn7-tf-1.11torch0.4keras2.2

from distutils.core import setup

setup(
    name='nsml vision hackathon',
    version='1.0',
    description='nsml vision hackathon',
    install_requires=[
        'scikit-learn'
    ]
)

```
