### ISSUE TITLE
fatal msg

### ISSUE THREAD

**Issue by HyunjiEllenPak** [AiHackathon2018/AI-Vision#114]
### 기타
![fatal](https://user-images.githubusercontent.com/16814077/50758563-e1e07c00-12a5-11e9-9ee5-0041b79f8ec1.PNG)
nsml run이 그동안 잘 실행되다가 갑자기 위와 같은 에러가 나는데 , 무슨 문제인지 모르겠는데 , 혹시 서버 내부 문제일까요?ㅠㅠ

**Comment by nsml-admin** [comment]
경로 오류로 보여집니다. 
해당 위치에 main.py 가 없거나, 시작 위치가 과거와 달라서 발생하는 듯 합니다.  
-ykkim-

**Comment by jireh-father** [comment]
@HyunjiEllenPak 

저도 동일한 문제가 있었는데요
main.py와 동일한 디렉토리에 정체불명의 nsml 이라는 빈 파일이 있어서
지웠더니 정상적으로 실행됐습니다.

**Comment by HyunjiEllenPak** [comment]
@nsml-admin @jireh-father 네,답변 감사드립니다. 제가 파일위치를 잘못적어서 발생한 문제였습니다ㅠ;;
