### ISSUE TITLE
nsml login 에러

### ISSUE THREAD

**Issue by dneirfi** [AiHackathon2018/AI-Vision#117]
```
INFO[2019/01/08 00:32:16.581] connecting to hack-cli.nsml.navercorp.com:18553 
INFO[2019/01/08 00:32:31.583] could not get the update URL: rpc error: code = DeadlineExceeded desc = context deadline exceeded 
FATA[2019/01/08 00:32:31.583] please check your network connectivity by using 'ping hack-cli.nsml.navercorp.com' 

```
며칠전에 잘되었는데 오늘 nsml login 시도하니 위와 같은 에러가 발생하였습니다.
nsml 웹상에서는 로그인 되며 nsml 재설치 후에도 위와 같은 에러가 발생하였습니다.

nsml whoami 시에도 아래와 같은 에러가 납니다.

`FATA[2019/01/08 00:27:04.099] could not execute internal: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: i/o timeout" 
`

**Comment by nsml-admin** [comment]
아래 명령을 실행후, 다시 시도해보시기 바랍니다. 
$ rm -f ~/.nsml_auth
$ rm -f ~/.nsml_cert

그리고, 재설치하신 이유를 알수있을까요? 뭔가 문제가 있었나요?

**Comment by dneirfi** [comment]
감사합니다.

nsml login error 관련 이슈를 찾아보니 어떤분이 재설치 하니 해결되었다해서 재설치해보았던것입니다.

**Comment by dneirfi** [comment]
nsml login 에러 관련 이슈를 찾아보다가 어떤분이 재설치 하니 해결되었다고 하셔서 저도 재설치 해보았던 것입니다. 

에러 해결되었습니다. 감사합니다.
