### ISSUE TITLE
[SOLVED] "https://hack.nsml.navercorp.com/" github 로그인  

### ISSUE THREAD

**Issue by insurgent92** [AiHackathon2018/AI-Vision#122]
nsml 로그인 시 github로 로그인하는 페이지가 사라졌습니다. 

![image](https://user-images.githubusercontent.com/15168540/50810497-46a2e180-134d-11e9-937f-fe2ea38bc88b.png)

**Comment by DaehunGwak** [comment]
저도 궁금합니다!

**Comment by sunnys-lab** [comment]
저도 동일한 현상이 있습니다. 무엇인가를 바꾸시려 하시는것 같은데.. 먼저 공지하고 해 주시면 좋을거 같습니다... ㅠ.ㅠ

**Comment by nsml-admin** [comment]
13:45~14:13까지 웹화면에 로그인 오류가 있습니다. 
CLI 및 서버에서 진행중인 학습에는 영향이 없으며, 다시 로그인하시면 됩니다. 
불편을 드려서 죄송합니다.

**Comment by insurgent92** [comment]
@nsml-admin :D 감사합니다.  
이렇게 뜻 깊고 재미있는 행사를 마련해 주셔서 감사할 따름입니다.
