### ISSUE TITLE
NSML tutorial login error

### ISSUE THREAD

**Issue by ChanHyeok** [AiHackathon2018/AI-Vision#13]
D:\Program Files>nsml login
INFO[2018/12/27 14:27:41.684] connecting to hack-cli.nsml.navercorp.com:18553
INFO[2018/12/27 14:27:42.041] could not get the update URL: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: EOF"
FATA[2018/12/27 14:27:42.064] please check your network connectivity by using 'ping hack-cli.nsml.navercorp.com'

D:\Program Files>ping hack-cli.nsml.navercorp.com

Ping slb-1038770.ncloudslb.com [210.89.187.57] 32바이트 데이터 사용:
210.89.187.57의 응답: 바이트=32 시간=16ms TTL=52
210.89.187.57의 응답: 바이트=32 시간=14ms TTL=52
210.89.187.57의 응답: 바이트=32 시간=16ms TTL=52
210.89.187.57의 응답: 바이트=32 시간=14ms TTL=52

210.89.187.57에 대한 Ping 통계:
    패킷: 보냄 = 4, 받음 = 4, 손실 = 0 (0% 손실),
왕복 시간(밀리초):
    최소 = 14ms, 최대 = 16ms, 평균 = 15ms

위와 같은 에러가 발생합니다.

**Comment by nsml-admin** [comment]
안녕하세요.
혹시 터미널이 윈도우의 `mingw`를 사용하시는건가요?

**Comment by ChanHyeok** [comment]
nsml 재설치하여 해결하였습니다.
