### ISSUE TITLE
[Solved]SUBMIT 시 ResourceExhaustedError 에러

### ISSUE THREAD

**Issue by SONG-WONHO** [AiHackathon2018/AI-Vision#130]
ResourceExhaustedError에러가 뜹니다!

테스트 셋이 한번에 들어와서 이런 에러가 발생하는걸로 예상되는데 해결을 위해선 인퍼함수에서 테스트셋을 분할 예측하면 될까요?

**Comment by nsml-admin** [comment]
네 infer함수에서 테스트셋을 분할예측해도 될것같습니다.

다만 infer함수에서 return할때 inference의 결과값과 input으로 들어온 query의 개수가 같아야 한다는걸 유의하시기바랍니다.
