### ISSUE TITLE
세션이 계속 Allocating! 중입니다

### ISSUE THREAD

**Issue by inch307** [AiHackathon2018/AI-Vision#143]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows
- **client version(please show nsml --version)**:
Built: 2019-01-10T17:16:19+09:00
Go: go1.11.4
GOARCH: amd64
GOOS: windows
Protocol: 20181214
Revision: cb3f66b5c345e62119237b5793139abee887eb5b (not-modified)
Preconfigured connection: hack-cli.nsml.navercorp.com
- **전체 실행 명령어**: nsml run -d ir_ph1_v2

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**: https://hack.nsml.navercorp.com/terminal/Avian_Influenza/ir_ph1_v2/79

**NSML login ID 가 무엇인가요?**
inch307

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**
Avian_Influenza/ir_ph1_v2/79
계속해서 allocating 중입니다.

Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !Allocating !

**재현방법은 어떻게 되나요?**
run을하고  Building docker image 중에 컨트롤 c를 눌렀습니다.
웹에서도 계속 할당중! 이라고 뜨길래 스탑 버튼을 눌렀는데도 계속 할당중! 이네요

**예상했던 동작방식은 무엇인가요?**
세션이 멈추길 바랬는데 계속 저모양이네요.

**제안하고 싶은 해결방법이 있나요?**
allocating!을 멈춰주세요 !

**Comment by DevKiHyun** [comment]
저도 발생합니다... 이거 gpu 사용량 계속 잡아먹는 것 아닌가요?????
 Resource_exhausted/ir_ph1_v2/396 에서 계속 발생합니다...

**Comment by Hackoperation** [comment]
위 현상은 재현 방법에 설명해 주신 대로 세션 준비 중에 비정상적으로 종료되었을 경우 발생하는 문제 입니다.

비정상적으로 생성되었던 세션은 일정 시간 이후에 정리가 되므로 크게 신경 쓰지 않으셔도 될 것 같습니다.

감사합니다.
