### ISSUE TITLE
setup.py 에서 cv2설치시 에러가 발생합니다.

### ISSUE THREAD

**Issue by jireh-father** [AiHackathon2018/AI-Vision#148]
`#nsml: nsml/ml:cuda9.0-cudnn7-tf-1.11torch0.4keras2.2

from distutils.core import setup

setup(
    name='nsml vision hackathon',
    version='1.0',
    description='nsml vision hackathon',
    install_requires=[
        'opencv-python'
    ]
)`

cv2를 설치하기 위해 setup.py 를 위처럼 세팅하고 run하면
아래 처럼 에러가 발생합니다.
제가 뭔가 잘못 설정한걸까요?
확인 부탁드립니다~

Installing collected packages: opencv-python, nsml-vision-hackathon
[91mCould not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.5/site-packages/cv2/LICENSE.txt'

[0m
jireh_family/ir_ph1_v2/213: building is failed
[]
Done
Error: Failed to build docker image

**Comment by Hackoperation** [comment]
안녕하세요.

위의 도커이미지에는 이미 opencv-python가 설치되어있습니다. 아마 도커환경에서 opencv-python을 또설치하다가 에러가 발생한것 같습니다.

따로 setup.py에 opencv를 추가하지말고 실행시키면 정상적으로 사용가능 합니다

감사합니다.

**Comment by jireh-father** [comment]
@Hackoperation 빠른 답변 감사드립니다!
제가 착각을 했었습니다.
cv2가 아니라 sklearn을 설치해야 되는거였네요 ;;
