### ISSUE TITLE
Transfer learning으로 하신 분이 있으신가요

### ISSUE THREAD

**Issue by SeoGyuSik** [AiHackathon2018/AI-Vision#177]
### 기타

...Failed to connect to tcp://10.34.33.99 with internal error
Failed to connect to tcp://10.34.30.210 with internal error
Cannot connect to the scheduler ... NSML is terminated
Since cluster does not have enough computing resources, job has been aborted. Please retry later
Error: No machine available that meets ALL your request such as CPU, RAM, Disk, GPU or its driver version
time="2019/01/15 01:26:02.189" level=fatal msg="Internal server error"

imagenet에 대한 pre-trained model의 가중치를 가져올때 이런 오류가 뜨는데
메모리 문제 어떻게 해결하셨나요? ㅜㅜ

**Comment by insurgent92** [comment]
@SeoGyuSik 안녕하세요! 
에러메시지를 읽어보시면 아시겠지만 해당 오류는 말씀하신 내용과 무관합니다.
작성자분이 요청하신 세션에 부합하는 computing resources를 찾기 못했다는 인데
다시말해 지금 nsml 서버에 세션이 들어갈 자리가 없다는 뜻입니다

**Comment by SeoGyuSik** [comment]
헉.. 저는 다른 문제인줄 알고 어제 오류보고 포기했었는데... 지금돌리니까 잘 되네요 감사합니다! ㅜㅜ
