### ISSUE TITLE
OOM에러

### ISSUE THREAD

**Issue by SeoGyuSik** [AiHackathon2018/AI-Vision#179]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows10
- **client version(please show nsml --version)**: 
- **전체 실행 명령어**: nsml submit gazua/ir_ph1_v2/52 19
#### WEB
- **Brower (chrome, firfox, etc)**: 
- **URL**:

**NSML login ID 가 무엇인가요?**
SeoGyuSik

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**
Building docker image. It might take for a while
..........Traceback (most recent call last):
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1127,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node block1_conv1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](block1_conv1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, block1_conv1/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**재현방법은 어떻게 되나요?**

**예상했던 동작방식은 무엇인가요?**

**제안하고 싶은 해결방법이 있나요?**
oom에러날때 infer함수에서 한꺼번에안들어오고 2번씩나눠서들어오게 하면 해결되나요?

**Comment by SeoGyuSik** [comment]
Infer함수를 (예를 들어 batch를 나눈다) 와 같이 최적화한다는게 무슨 의미인지 감이 잡히지 않습니다.. 
좀더 자세히 설명해주실 수 없으신가요?.. Infer에서 정확히 어느 부분에서 그래픽카드 메모리가 넘치는 문제가 생긴건지 모르겠습니다.. Infer에서 고쳐야할 부분이 어디인가요?

**Comment by yanghoJI** [comment]
혹시 도움이 되실까 싶어 글 남겨요
1127개 샘플을 한번에 모델에 넣는게 아니라 밑처럼 
몇 배치로 쪼개서 넣어주어 합치면 메모리 문제가 나지 않습니다.

qfeatures = torch.zeros(len(queries), 512, dtype=torch.float)
endbatch = len(queries) // batch_size
            if len(queries) % batch_size != 0:
                endbatch += 1
            for batidx in range(endbatch):
                st = batidx * batch_size
                en = min((batidx + 1) * batch_size, len(queries))
                xbatch = query_img[st: en, :, :, :]
                qfeatures[st: en, :] = feature_model(xbatch.to(device))

**Comment by nsml-admin** [comment]
안녕하세요
infer함수에 입력되는 queries와 reference의 수는 195, 1127개 입니다.

모델을 inference할때 @yanghoJI 님이 설명해주신대로 배치로 하면 OOM이슈는 피할수있을거라고 생각됩니다.

전체 에러로그는 다음과같습니다
```python
File "main.py", line 71, in infer
    reference_vecs = get_feature_layer([reference_img, 0])[0]
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1127,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node block1_conv1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](block1_conv1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, block1_conv1/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```

**Comment by SeoGyuSik** [comment]
> 혹시 도움이 되실까 싶어 글 남겨요
> 1127개 샘플을 한번에 모델에 넣는게 아니라 밑처럼
> 몇 배치로 쪼개서 넣어주어 합치면 메모리 문제가 나지 않습니다.
> 
> qfeatures = torch.zeros(len(queries), 512, dtype=torch.float)
> endbatch = len(queries) // batch_size
> if len(queries) % batch_size != 0:
> endbatch += 1
> for batidx in range(endbatch):
> st = batidx * batch_size
> en = min((batidx + 1) * batch_size, len(queries))
> xbatch = query_img[st: en, :, :, :]
> qfeatures[st: en, :] = feature_model(xbatch.to(device))

제가 pytorch를 쓰지 않고 초보여서 그런지 잘 이해가 안되네요 ㅜㅜ
저는 베이스라인 if __main__부분만 수정하고 infer()을 그대로 쓰고 있었는데요...
# caching db output, db inference
        db_output = './db_infer.pkl'
        if os.path.exists(db_output):
            with open(db_output, 'rb') as f:
                reference_vecs = pickle.load(f)
                print(reference_vecs)
        else:
            reference_vecs = get_feature_layer([reference_img, 0])[0]
            print(get_feature_layer([reference_img, 0]))
            print(reference_vecs)
            with open(db_output, 'wb') as f:
                pickle.dump(reference_vecs, f)
                print(reference_vecs)
여기에서 else: 이하를 고치면 되는걸까요..? ㅜㅜ 아직도 해결을 못하고 있어서 죄송합니다..

**Comment by yanghoJI** [comment]
현재 테스트해 볼 환경이 아니여서 그냥 코드만 적었습니다.

~~~

db_output = './db_infer.pkl'
if os.path.exists(db_output):
    with open(db_output, 'rb') as f:
        reference_vecs = pickle.load(f)
else:
    batch_size = 128
    reference_vecs = get_feature_layer([reference_img, 0])[0]
    # 512 = 모델 특징벡터 아웃풋 크기.
    reference_vecs = np.zeros(reference_img.shape[0], 512, dtype=np.float32)    
    endbatch = reference_img.shape[0] // batch_size
    if reference_img.shape[0] % batch_size != 0:
        endbatch += 1
    for batidx in range(endbatch):
        st = batidx * batch_size
        en = min((batidx + 1) * batch_size, reference_img.shape[0])
        xbatch = reference_img[st: en, :, :, :]
        reference_vecs[st: en, :] = get_feature_layer([xbatch, 0])[0]  
    with open(db_output, 'wb') as f:
        pickle.dump(reference_vecs, f)


~~~

**Comment by SeoGyuSik** [comment]
정말 감사합니다...! ㅜㅜㅜ
