### ISSUE TITLE
nsml.cache를 사용하지 않아도되나요?

### ISSUE THREAD

**Issue by suwoncjh** [AiHackathon2018/AI-Vision#210]
dataset feeding중에 nsml.cache를 그냥 지워버리고 사용중인데요 
nsml.report와 nsml.save가 모두 동작이 하지 않는것같은데 (graph 출력안되고, 세션모델이 저장안됨) 
cache를 안써서 그런것인가요?

**Comment by suwoncjh** [comment]
제가 실수를 했네요 cache없어도 graph출력되고 세션모델 저장되는걸 확인했습니다.

**Comment by nsml-admin** [comment]
안녕하세요.

네! 해결되셨다니 다행입니다. 
해당 건과 관련하여 이후에도 문의할 내용이 없으시면 이슈 close를 부탁드리겠습니다.
