### ISSUE TITLE
submit 으로 제출할 시 cpu와 gpu 개수 

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#212]
submit으로 서버에서 infer를 돌리고 있는 경우
할당되는 cpu 개수가 어떻게 됩니까?
nsml run과 마찬가지로 -c 를 통해 cpu를 정해서 할당할 수 있었는데
submit 에서는 고정으로 6개 정도를 할당하나요?
데이터가 너무 많아져서 cpu가 많이 필요할 것 같습니다..

**Comment by nsml-admin** [comment]
안녕하세요.

`submit` 에서는 cpu개수가 4개로 고정되어있고 따로 지정할수는 없습니다. 만약 데이터가 많아져서 메모리가 문제가된다면 generator를 활용해보시면 어떨까요? https://github.com/AiHackathon2018/AI-Vision/issues/197

감사합니다.

**Comment by DevKiHyun** [comment]
최적화를 잘 해야된다는 것은 의견이 없지만 개인적으로 데이터양이 상당히 커졌는데 제출 시 주어지는 1시간이 너무 짧은 것 같네요...

**Comment by nsml-admin** [comment]
@DevKiHyun 

제한된 1시간의 submit 시간은 abusing을 막기 위한 최대 한도로 책정한 사안입니다.
혹시 이전 예선과 비교해서 timeout 시간이 얼마나 더 필요하신지 알 수 있을까요?

@ttagu99 
말씀은 submit -t로했을때 10개의 데이터셋이 아니라, 전체 set으로(트레이닝 셋이겠죠?) infer함수 로그를 찍어봤으면 좋겠다는건가요? 좋은아이디어인것 같습니다. 저희팀에서 따로 논의해보도록 하겠습니다.

두분다 좋은의견 감사합니다.

**Comment by DevKiHyun** [comment]
nsml 서버의 성능은 불만이 없지만 서버 내에서 submit이 이루어져야 되고 그 이외에 개인 storage가 주어지지 않는 경우를 고려했을때 2차전은 데이터 용량상 1차전의 기준으로 2~3배의 제출 시간을 주어야 되지 않을까 싶습니다. 물론 1시간동안 제출을 못하게 하는건 전적으로 동의를 합니다. 물론 대회라는 것은 최대한의 기술을 발휘하는 것이 맞겠지만, nsml 상의 보안과 여러 문제로 인해 자유도가 제한된 이상 적어도 제출시간은 길어도 되는게 아닐까 싶습니다.

**Comment by ttagu99** [comment]
> @DevKiHyun
> 
> 제한된 1시간의 submit 시간은 abusing을 막기 위한 최대 한도로 책정한 사안입니다.
> 혹시 이전 예선과 비교해서 timeout 시간이 얼마나 더 필요하신지 알 수 있을까요?
> 
> @ttagu99
> 말씀은 submit -t로했을때 10개의 데이터셋이 아니라, 전체 set으로(트레이닝 셋이겠죠?) infer함수 로그를 찍어봤으면 좋겠다는건가요? 좋은아이디어인것 같습니다. 저희팀에서 따로 논의해보도록 하겠습니다.
> 
> 두분다 좋은의견 감사합니다.

 네 감사합니다.  나중에 생각한거긴 한데. 단순 infer함수의 속도 개선이 목적이라면, 아래처럼 10개 제공된 image list를 아래처럼 갯수만 맞춰줘도 가능합니다. 참고하세요~.
        # debuging all set size
        # queries = query_img*901
        # references = references*3674
        # query_img = query_img*901
        # reference_img = reference_img*3674

training set으로 submit 해보는 옵션이 있다면 최고 일거 같습니다. map@1000까지 계산된다면, test 점수가 안나올때 overfit 되서 안나오는건지, underfit 되서 안나오는건지, train 자체를 잘못한건지, 모델링할때 디버깅하기가 훨씬 수월해질거 같습니다~.

**Comment by DevKiHyun** [comment]
nsml 서버가 설계한 제출 구조에 대해 말씀해주신걸 들어보니 1시간 제한과 1시간 이내 끝나도록 하는게 타당한 것 같습니다. 1시간 안에 최대한의 능력을 발휘해보도록 하겠습니다!
