### ISSUE TITLE
데이터를 읽다가 해당 프로세스가 킬 당하는데 어떻게 핸들링해야 할까요?

### ISSUE THREAD

**Issue by DaehunGwak** [AiHackathon2018/AI-Vision#213]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
Windows 10 HOME

- **client version(please show nsml --version)**:
![image](https://user-images.githubusercontent.com/12469427/51656055-d057dd80-1fe2-11e9-97c5-95ac6f67ee1f.png)

- **전체 실행 명령어**:
`nsml run -d ir_ph2 `

#### WEB
- **Brower (chrome, firfox, etc)**:
chrome

- **URL**:

**NSML login ID 가 무엇인가요?**
DaehunGwak

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**
![image](https://user-images.githubusercontent.com/12469427/51656096-07c68a00-1fe3-11e9-8d1c-100633e5752d.png)
  * session : `rev: 6`
  * 내용 : 기존 베이스라인으로 데이터를 읽다가 해당 프로세스가 kill 당합니다.

**재현방법은 어떻게 되나요?**

**예상했던 동작방식은 무엇인가요?**

어떻게 데이터를 불러야 할 지 모르겠는데, 데이터를 generator를 만들어 배치단위로 feeding 해야하는 건가요?

**제안하고 싶은 해결방법이 있나요?**

어떻게 해결해야할 지 잘모르겠습니다..

**Comment by nsml-admin** [comment]
데이터사이즈가 약 10배정도 커져서
기존처럼 데이터로더를 통해서 데이터를 읽어오면 메모리 에러가발생할수있습니다.
https://github.com/AiHackathon2018/AI-Vision/issues/197 를 참고하시면 도움이 될것같습니다.

감사합니다.

**Comment by DaehunGwak** [comment]
@nsml-admin 
``` python
datagen = ImageDataGenerator(rescale=1./255., validation_split=VAL_RATIO)
train_gen = datagen.flow_from_directory(train_dataset_path, target_size=input_shape[:2] 
                                        batch_size=BATCH_SIZE, subset="training")
val_gen = datagen.flow_from_directory(train_dataset_path, target_size=input_shape[:2],
                                      batch_size=BATCH_SIZE, subset="validation")

...
model.fit_generator(train_gen,
                    steps_per_epoch=(num_total * (1 - VAL_RATIO)) // BATCH_SIZE,
                    initial_epoch=epoch,
                    epochs=epoch + 1,
                    callbacks=[reduce_lr],
                    validation_data=val_gen,
                    validation_steps=(num_total * VAL_RATIO) // BATCH_SIZE,
                    verbose=1)
```
오 감사합니다! 
답변덕분에 해결할 수 있었습니다. 
앞으로 공지 잘 읽어보겠습니다..
