### ISSUE TITLE
다른 세션에 저장된 모델을 불러오는 예제는 어디있나요?

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#214]
이전 세션에 저장한 모델을 load해오는 예제가 있나요? 비슷하게 설명이 있는 것 같은데 이해하기가 힘듭니다. keras를 이용하고 있는데 어떻게 할 수 있는지 알려주시면 감사합니다.

**Comment by nsml-admin** [comment]
`nsml.load()`를 이용하는 방법인데요,

https://n-clair.github.io/vision-docs/_build/html/ko_KR/contents/load_model.html 를 참고하시면될것같습니다.

**Comment by DevKiHyun** [comment]
해결했습니다. 제가 space가 하나 들어가서 문제였던 것 같습니다.
