### ISSUE TITLE
submit 시 test_data_loader 호출에 따른 image 개수 차이

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#220]
네이버측의 baseline에서 보면

```
def infer(queries, db):
        queries, query_img, references, reference_img = preprocess(queries, db)
```

이렇게 되어있습니다.
submit -t 를 할 경우엔 이번 2차전에선 10개 밖에 못 불러오게 되어있습니다.
만약 그냥 제출로 할 경우 내부에서 확실하게 test data query의 50퍼센트만 불러오게 되나요?

예선 1차에선 아래와 같이 해야 195개의 query가 불러와졌습니다.
```
def infer(queries, db):
        queries, db = test_data_loader(DATASET_PATH)
        queries, query_img, references, reference_img = preprocess(queries, db)
```
이번 2차전에서는 이렇게 할 경우 50퍼센트만 불러오나요? 아니면 전체를 불러오나요?

**Comment by Hackoperation** [comment]
안녕하세요.
Vision팀의 고병수 멘토입니다.

submit -t를 할 경우에는 10개의 데이터만 테스트용으로 사용할 수 있습니다.
submit을 할 경우에는 예선 2라운드/결선(온라인)에서는 test data query의 50%만 자동으로 불러오게 됩니다.
사실 현재 NSML에 저장되어 있는 데이터가 test data query의 50%만 있고, 결선(오프라인)때 나머지 데이터를 업로드 할 예정입니다.

감사합니다.
