### ISSUE TITLE
자원 할당에 문제가 있는 것 같습니다...

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#238]
gpu 1개만 사용하는데도 지금 자원 할당을 못받고 있습니다...
지금 사용현황을 보는데 너무 부족한것 같은데... 이럴땐 어떻게 해야하나요?

**Comment by bluebrush** [comment]
@DevKiHyun 일시적으로 자원요구가 몰리면서 부족현상이 있었습니다. MAX GPU값을 조정하여 곧 부족현상이 다소 해소될 것으로 예상됩니다.

**Comment by DevKiHyun** [comment]
submit -t 단계에서 cpu를 확인해보니 8개로 출력이 되었습니다.
제출 단계에서도 이 개수가 동일하게 적용되나요?
multiprocessing.cpu_count()로 확인해본 개수입니다.

**Comment by nsml-admin** [comment]
`submit -t` 와 `submit`의 cpu 개수는 동일하게 적용됩니다.

**Comment by DevKiHyun** [comment]
감사합니다~
