### ISSUE TITLE
참가 신청 변경 내용이 있습니다.

### ISSUE THREAD

**Issue by mojoblue** [AiHackathon2018/AI-Vision#24]
팀 명을 한글로 잘못 등록해 영문으로 변경하려 합니다.
기존 팀명은 "하쿠나 마타타" 이고 "Hakuna-matata"로 변경 부탁드립니다.
팀 멤버는 이세희, 우지철입니다.

**Comment by Hackoperation** [comment]
네 반영드렸습니다.

고맙습니다.^^
