### ISSUE TITLE
submit -t 에선 문제가 없으나 제출할 시 에러가 뜹니다.

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#243]
267 세션을 하고 

```
........
Building docker image. It might take for a while
..........Traceback (most recent call last):
TypeError: 'int' object is not iterable

..Error: Fail to get prediction result: Resource_exhausted/ir_ph2/262/0
FATA[2019/01/28 16:19:34.209] Internal server error
```

위와 같은 에러가 출력됩니다.
submit -t 에선 문제가 없는데 왜 뜨는지 모르겠습니다. 결과 리스트를 반환하는 부분이
생략되었나 하고 확인했으나 정상적으로 코드가 존재합니다.

**Comment by HyunjiEllenPak** [comment]
@DevKiHyun 저 혹시 테스트 제출할 떄 소요시간이 얼마나 걸리시나요?!

**Comment by DevKiHyun** [comment]
@HyunjiEllenPak  테스트로는 전체적으로 3분안에 끝난 것 같습니다.

**Comment by insurgent92** [comment]
@DevKiHyun 어떤 문제였는지 저도 궁금하네요 
TypeError: 'int' object is not iterable 라면 summit -t 에서는 왜 에러가 발생하지 않았나요?

**Comment by DevKiHyun** [comment]
@insurgent92  코드 설계상 자세하게 답은 못드리지만 아마 에러가 발생하지 않은게 아니라 에러 로그가 정상적으로 출력되지 않은것 같습니다.
