### ISSUE TITLE
test data 경로를 찾을 수 없습니다. 

### ISSUE THREAD

**Issue by yunsu3042** [AiHackathon2018/AI-Vision#246]
**Informations**
기존의 nsml/ml:cuda9.0-cudnn7-tf-1.11torch0.4keras2.2에 라이브러리를 추가하여 yunsu/golden_retrieval:1 이미지를 허브에 올려 다음과 같이 사용했습니다. 

#nsml: yunsu/golden_retrieval:1
from distutils.core import setup

setup(
    name='nsml vision hackathon',
    version='1.0',
    description='nsml vision hackathon',
    install_requires=[
        "sklearn",
        "tensorflow_hub",
        "scikit-image"
    ]
)

#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
Built: 2019-01-23T18:07:25+09:00
Go: go1.11.4
GOARCH: amd64
GOOS: darwin
Protocol: 20181214
Revision: 1f6a758e6d9a2c0e5bdc8e439394a9259213cd8a (not-modified)
Preconfigured connection: hack-cli.nsml.navercorp.com

- **전체 실행 명령어**:
nsml run -d ir_ph2 -e main.py

**NSML login ID 가 무엇인가요?**
yunsu3042

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**

Golden_Retrieval/ir_ph2/88

![Imgur](https://i.imgur.com/hAQzFyB.png)

**재현방법은 어떻게 되나요?**
nsml run -d ir_ph2 -e main.py

**예상했던 동작방식은 무엇인가요?**
[os.path.join(test_path, 'reference', path) for path in os.listdir(os.path.join(test_path, 'reference'))]
를 실행했을 때 이미지의 절대 경로들을 리스트로 반환할 것을 기대했지만  
 [Errno 2] No such file or directory: '/data/ir_ph2/test/test_data/reference'가 발생했습니다. 

기존의 main.py에서 잘 동작하던 코드이고 경로에 문제가 없는 것 같아 의문이 듭니다. 

**제안하고 싶은 해결방법이 있나요?**
# #

**Comment by nsml-admin** [comment]
안녕하세요,
training세션에서는 test 데이터셋에 접근할수없습니다.
test데이터에  접근할수있는 시점은 `submit`또는 `submit -t` 입니다.

위 에러는 도커이미지와는 상관이 없어보입니다.

**Comment by yunsu3042** [comment]
감사합니다. 
제가 train data와 햇갈렸습니다.
