### ISSUE TITLE
session 학습중인데 zombie라고 출력됩니다.

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#247]
292 세션 학습중인데
평소면 running이라고 떠야되는데
이번엔 zombie라고 뜹니다.
학습은 계속해서 되는것 같습니다만... 불안합니다.

**Comment by nsml-admin** [comment]
@DevKiHyun zombie라고 표시되어도 학습에는 영향을 주지 않습니다.  안심하셔도 됩니다. 
상태가 바뀐 이유를 확인후 조치하도록 하겠습니다.

**Comment by DevKiHyun** [comment]
감사합니다 ㅎㅎ
