### ISSUE TITLE
validation dataset 생성에 따른 permission error

### ISSUE THREAD

**Issue by nakyilkim** [AiHackathon2018/AI-Vision#248]
### 기타

안녕하세요, train data를 복사한 후 일부를 삭제하여 validation set을 만들고자 합니다.
하지만 PermissionError로 인하여 실행이 불가능합니다.  기존 1차 예선에서는 데이터 수가
몇 개 되지 않아서 전체 데이터를 불러온 후에 나눌수 있었지만 현재는 데이터가 너무 크기
떄문에 위 방법이 불가능합니다. 혹시 validation 디렉토리를 새로 만들어서
트레인 데이터를 옮기는 작업은 금지가 되어 있는지 여쭈어보고 싶습니다.
감사합니다.

**Comment by yanghoJI** [comment]
제가 해본 결과 현재 코드가 돌아가는 경로 기준으로 상위 폴더에는 접근불가하지만 하위 폴더에 무언가를 복사하는 등의 작업은 가능 했습니다. 복사 경로를 './copypath' 와 같이 만들어 사용하시면 될 것 같습니다.

**Comment by nsml-admin** [comment]
@yanghoJI  님의 말씀처럼 하위폴더로 복사를 해주시면 됩니다.

train데이터를 다른 폴더로 옮기는 작업에대한 제한은 없습니다.

**Comment by nakyilkim** [comment]
감사합니다!
