### ISSUE TITLE
세션간 데이터 공유 문제

### ISSUE THREAD

**Issue by SONG-WONHO** [AiHackathon2018/AI-Vision#251]
**Informations**
#### CLI

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**
b1ackstone/ir_ph2/48

b1ackstone/ir_ph2/47세션에서 전처리된 데이터를 저장 후 b1ackstone/ir_ph2/48세션에서 이를 불러오고 싶습니다. 각 세션별로 샌드박스 환경이 구성되는것같은데 nsml에서 이를(이전 세션에서 저장된 전처리된 데이터) 공유할 수 있는 방법이 있을까요?

감사합니다.

**Comment by nsml-admin** [comment]
안녕하세요,

`nsml.cache()`를 이용하면 될것같은데요, 관련되어서는
1. https://github.com/AiHackathon2018/AI-Vision/labels/NSML-Cache
2. https://n-clair.github.io/vision-docs/_build/html/ko_KR/contents/nsml_library/nsml_cache.html

를 참고해주시기 바랍니다.

**Comment by SONG-WONHO** [comment]
넵 해결했습니다. 감사합니다!
