### ISSUE TITLE
-c 를 사용한 cpu 개수 질문입니다.

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#255]
cpu가 1~6 개 가량 할당되도록 조절이 가능한데
이때의 개수는 cpu의 물리적 개수를 의미하는 건가요
아니면 mulit core의 개수를 의미하는 건가요?
만약 -c가 순수 cpu의 개수를 의미하는 거라면 core의 개수도 알 수 있을까요?

**Comment by nsml-admin** [comment]
multi core를 의미합니다.  :) 
현재 해커톤의 인프라에서는 1GPU당 4core까지 권장합니다.

**Comment by DevKiHyun** [comment]
감사합니다~~
