### ISSUE TITLE
gpu 할당 문제

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#259]
안녕하세요
현재 저희 팀에서는 gpu를 2대만 사용하고 있는데
새로운 세션을 돌리면 아래와 같은 에러가 뜹니다.

```
...Error: Fail to run nsml session due to lack of available GPU for you
Your maximum available GPU is 5
Your are currently using 5 GPU
The number of GPU you requested is 1 GPU
```
제출하기전에 등록하는 세션이다 보니 돌리긴 해야되는데 
문구를 보면 저희가 더 많은 gpu를 사용하는것 같습니다.
세션을 2개만 돌려둔 상태라 gpu가 5개까지 사용될 일이 없을 것 같은데
왜 그러는지 모르겠습니다.

**Comment by DevKiHyun** [comment]
지금은 414 세션 외에는 돌리고 있는 세션이 없습니다.
414 는 학습 중인 세션이라 종료할 수 없고 나머지는 다 완료된 세션들이라
gpu가 5개가 사용되는 이유를 모르겠습니다.

**Comment by nsml-admin** [comment]
안녕하세요,

gpu장비 2개가 다운되는 현상이 있어서 gpu가 정상적으로 카운트가 되지않았던 문제로 보입니다.

현재는 정상적으로 돌아왔습니다

다시한번 확인부탁드립니다

감사합니다.

**Comment by DevKiHyun** [comment]
음.. 지금도 해결이 잘 안된 것 같습니다 ㅠ 지금도 고생 중이실텐데 한번 더 확인해주실 수 있으신가요?
