### ISSUE TITLE
요청하지 않은 gpu가 임의로 할당되어 있는 것 같습니다.

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#262]
현재 저희팀은 제출한 세션이 하나, 학습 중인 세션이 하나로 총 2개의 세션만 gpu가 돌아가는 상황입니다.
하지만 지금 세션을 하나 더 학습시키려고 gpu를 요청하니깐 
```
...Error: Fail to run nsml session due to lack of available GPU for you
Your maximum available GPU is 4
Your are currently using 4 GPU
The number of GPU you requested is 1 GPU
```

이렇게 뜨고 있습니다.
어디선가 2개의 gpu를 잡아먹고 있는건지 잘 모르겠습니다.
이것 때문에 원활한 진행이 되고 있지 않습니다...

**Comment by merturl** [comment]
저도 같은 증상을 겪고 있는데 Stop도 안됩니다.

**Comment by nsml-admin** [comment]
@DevKiHyun  노드가 다운되서 점유상태가 되었엇고 지금은 복구되어서 정상적으로 표시 될것 같은데 확인한번 부탁드립니다. (서브밋중인 세션도 같이 카운트되니 유의해주시기바랍니다.)

@merturl  stop이 안되는 세션네임을 알려주시면 도와드리겠습니다.

감사합니다.

**Comment by DevKiHyun** [comment]
감사합니다. 현재 잘 되는것 같습니다~~
