### ISSUE TITLE
모델 로그창이 format error 라며 보이지 않습니다.

### ISSUE THREAD

**Issue by Karnian** [AiHackathon2018/AI-Vision#273]
실행중인 혹은 이미 실행이 끝난 모델 정보를 보려고 하면 다음과 같이 나오지 않습니다.

![image](https://user-images.githubusercontent.com/28075892/52260217-b4502680-2968-11e9-88b4-ef729c81e8bc.png)

이전에 잘 보였었는데 갑자기 그러네요.

사용중인 다른 컴퓨터에서도 동일 현상이 발생합니다.

**Comment by nsml-admin** [comment]
관련된 에러가있어서 현재는 수정되었는데요,

다시한번 확인 부탁드립니다.
