### ISSUE TITLE
submit 후 에러 => Error: Fail to start docker container: b''  에러

### ISSUE THREAD

**Issue by sunnys-lab** [AiHackathon2018/AI-Vision#275]
submit 후 다음과 같은 에러가 종종 잡힙니다.=> Error: Fail to start docker container: b''  에러

해당 에러 발생 후 일정 시간 후에 다시 하면 되는 경우도 있지만..약 1시간동안 GPU를 선점하고 있는 경우도 있습니다. 원인 및 해결 방법 문의 드립니다.

감사합니다.

------------------------------------------------------------------------------------------------------------------------

root@ubuntu1804:/work/PycharmProjects/2019-NSML-AI-Vision# ./nsml submit Sunny/ir_ph2/261 33
........
Building docker image. It might take for a while
...Stopping Sunny/ir_ph2/-1 is failed
Done
Error: Fail to start docker container: b''
FATA[2019/02/05 18:13:30.646] Internal server error

**Comment by DevKiHyun** [comment]
제 gpu 할당문제가 이것때문에 생기는 것 같더라구요...

**Comment by ChungminPark** [comment]
저도 제출 할 때 빈번하게 같은 에러가 발생합니다. 에러 연속으로 두번 나면 대략 1시간 정도 GPU 2개를 사용하지 못합니다.. ㅠㅠ

**Comment by nsml-admin** [comment]
불편을 드려서 죄송합니다.

어제 관련 에러가 수정되었고 현재는 문제가발생하지 않을것으로 예상됩니다.

또 발생하면 리포트부탁드립니다.
