### ISSUE TITLE
예선 2차 끝나면 dataset board가 새로 변경되나요?

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#281]
예선 2차가 종료되면 
dataset board 가 새로 변경되나요?
예선 2차에 사용한 세션들을 계속해서
이용할 수 있는지 궁금합니다.

**Comment by nsml-admin** [comment]
leaderboard는 초기화되고 세션들은 남아있습니다.

**Comment by DevKiHyun** [comment]
감사합니다
