### ISSUE TITLE
gpu 할당 문제가 발생했습니다

### ISSUE THREAD

**Issue by smartdolphin** [AiHackathon2018/AI-Vision#284]
gpu 할당 문제가 발생했습니다.

![image](https://user-images.githubusercontent.com/2484502/52470569-d698ad00-2bd1-11e9-93c7-17032a67cd52.png)

**Comment by nsml-admin** [comment]
2차 예선은 16:00시 종료되었습니다.  nsml은 다음주 화요일 다시 open할 예정입니다. 일정 참고해주시기 바랍니다.
