### ISSUE TITLE
예선 2차와 지금 데이터가 동일한 query 개수인 것 같습니다.

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#288]
예선 2차와 결선과의 차이는 query를 50퍼센트로 제한했다는 걸로 알고 있는데
현재 query도 예선 2차와 동일하게 query가 50퍼센트로 제한되어있는 것 같습니다.

**Comment by nsml-admin** [comment]
안녕하세요.

현재는 전과 같이 50%의 데이터셋만 사용하고 결선(오프라인) 때 나머지 테스트데이터셋이 보충됩니다.

**Comment by DevKiHyun** [comment]
감사합니다.
