### ISSUE TITLE
Submit 시 error가 발생했는데 해당 세션들이 오랜 기간동안 사라지지 않습니다.

### ISSUE THREAD

**Issue by insurgent92** [AiHackathon2018/AI-Vision#289]
해당 세션(?)은 아래와 같습니다. 

![image](https://user-images.githubusercontent.com/15168540/52615854-fb469a80-2ed9-11e9-928f-37c5ec9a0289.png)

**Comment by nsml-admin** [comment]
안녕하세요.

submit도중 `ctrl+c` 등으로 비정상 종료가 된경우는 1시간정도 후에 자동으로 사라지게됩니다.

감사합니다.

**Comment by insurgent92** [comment]
@nsml-admin 감사합니다.
