### ISSUE TITLE
docker image에 설치된 패키지 관련  변경사항이 있나요?

### ISSUE THREAD

**Issue by ttagu99** [AiHackathon2018/AI-Vision#290]
기존에 submit 했던 session을 다시했는데 
nsml submit  Zonber/ir_ph2/312  secls_222_20

아래처럼 setup 과정중에 에러가 나옵니다.. docker image에 변경이 있는건가요?
'/opt/conda/lib/python3.5/site-packages/cv2/LICENSE.txt'

**Comment by insurgent92** [comment]
저도 동일한 문제를 겪고 있습니다.

**Comment by insurgent92** [comment]
@ttagu99 혹시 submit 말고 그냥 train은 잘 되시나요? 
동일한 코드인데 에러가..

**Comment by ttagu99** [comment]
> @ttagu99 혹시 submit 말고 그냥 train은 잘 되시나요?
> 동일한 코드인데 에러가..

 아뇨 저도 아직 안되고 있습니다. 동일한 코드였구요. 발생되는 에러는 
"ImportError: libSM.so.6: cannot open shared object file: No such file or directory"
입니다.

**Comment by nsml-admin** [comment]
안녕하세요.

cuda9.0-cudnn7-tf-1.11torch1.0keras2.2  에대한 변경사항은 있었지만
cuda9.0-cudnn7-tf-1.11torch0.4keras2.2 에 대한 변경사항은 없었습니다.

확인해보니 `imgaug` 패키지가 최근에 업데이트되면서 기존 환경과 호환이 안되는것같습니다.

`'imgaug==0.2.7'` 로 바꿔주시면 될 것 같습니다.

submit도 관련된 session을 training을 새로 시켜주셔야 할것같습니다.

감사합니다.

**Comment by ttagu99** [comment]
해결되었습니다~. 감사합니다.

**Comment by heasungkim** [comment]
@ttagu99 
안녕하세요, 같은 문제를 겪고 있는데 어떻게 해결하셨는지 궁금합니다.
