### ISSUE TITLE
계속 allocated 로 되어있는 세션이 있습니다.

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#296]
745 세션이 지금 취소가 안되고 allocated 되어있습니다.
죄송하지만 혹시 취소해주실수 있으신가요?

**Comment by nsml-admin** [comment]
취소해드렸습니다.

**Comment by heypaprika** [comment]
저희도 같은 문제가 생겼는데, artint 팀 386번 세션 취소 부탁드려도 될까요?
