### ISSUE TITLE
infer 관련해서 에러로그 부탁드립니다.

### ISSUE THREAD

**Issue by chrisfy7** [AiHackathon2018/AI-Vision#297]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: windows
- **client version(please show nsml --version)**:
- **전체 실행 명령어**: nsml submit -t Avantgarde_Vision/ir_ph2/681

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**NSML login ID 가 무엇인가요?**
chrisfy7

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**
Avantgarde_Vision/ir_ph2/681

**재현방법은 어떻게 되나요?**

**예상했던 동작방식은 무엇인가요?**

**제안하고 싶은 해결방법이 있나요?**

**Comment by nsml-admin** [comment]
안녕하세요.

메일에서도 답변드렸지만 submit -t 로하면 세션이 사라지지않고 `nsml logs`를 통해 세션로그를 확인할수있는데요,
print로 각변수들을 확인하면서 디버깅을 해보시기 바랍니다.

감사합니다.

**Comment by chrisfy7** [comment]
로그 확인은 가능한데 몇 번째 줄에서 오류가 난건지 확인이 안되는것 같아서요. 확인 가능한 방법이 없나요?

**Comment by nsml-admin** [comment]
에러로그는 다음과같습니다.
```python
Traceback (most recent call last):
  File "main.py", line 55, in infer
    queries, query_vecs, references, reference_vecs = get_feature(model, queries, db)
  File "main.py", line 124, in get_feature
    for i, (images, labels) in enumerate(query_loader):
ValueError: too many values to unpack (expected 2)
```
