### ISSUE TITLE
Vision 공부방법 질문드리고싶습니다.

### ISSUE THREAD

**Issue by CruxSungukJung** [AiHackathon2018/AI-Vision#309]
컴공과 3학년 학생입니다. 1차는 어찌어찌 겨우 붙었는데 2차때는 아쉽게 떨어졌습니다.
공부한지 얼마안되서 겨우 인셉션모델, vgg16 이런거 가져와서 쓰는 정도 밖에안되었고 대회때 처음으로 논문보면서 논문에 있는 모델을 구현하려고 몇번 시도해보고 이제 비전 쪽에 발은 담군것 같은 느낌이 들었습니다. 제 실력이 부족한탓에 vgg나 인셉션을 가져와서 튜닝을 잘못해서 그런지 잘 성능이 나오지 않더군요 ㅠㅠ 

이런질문을 드려도 괜찮을지 모르겠지만, 1차나 2차때 image retrival 같은 문제를 해결하기 위해서는 어떤 부분을 공부하면 될까요?

실례가 안된다면, 노하우좀 알려주시면 감사하겠습니다 ㅠ

**Comment by HeysenChoi** [comment]
안녕하세요. 저도 이번에 처음으로 딥러닝을 공부해봐서 디테일한 공부방법은 다른 전공자분들이 말씀해주시는 게 좋을 거 같네요.  대신 제가 이번 대회에서 사용한 모델을 말씀드리겠습니다.

DenseNet201 + concat(R-MAX,GeM) + PCA + DBA + QE
Classification으로 트레이닝하였으며 lr는 1e-05~06 수준으로 미세하게 하였습니다.

**Comment by CruxSungukJung** [comment]
오오 저렇게 짜셨군요 대략적인 퍼포먼스는 어느정도 나오셨나요?

**Comment by HeysenChoi** [comment]
최종 점수 약 0.95로 7등이였습니다.
다양한 논문 읽어보고, 체계적으로 좋은 성능 내는 모델을 찾아가는게 중요하더라구요.

**Comment by CruxSungukJung** [comment]
감사합니다 ㅠㅠㅠ 매우 귀중한 팁이군요
