### ISSUE TITLE
논문 관련 문의 드립니다.

### ISSUE THREAD

**Issue by DaehunGwak** [AiHackathon2018/AI-Vision#315]
안녕하세요. 24시간이모자라 팀의 곽대훈입니다.

해당 대회에서 진행했던 실험들이 아까워 기록으로 남기고자,

학부생 논문 세션에 제출하고자 하는데 괜찮을까요?

다음 학회에 제출하고자 합니다.
http://www.kiise.or.kr/conference/kcc/2019/

**Comment by kobiso** [comment]
[해커톤 메인페이지](https://campaign.naver.com/aihackathon2018/)의 FAQ에 아래와 같이 공지하였습니다.

>Q) 해커톤에서 개발한 알고리즘을 개인 논문에 사용해도 되나요?
다음 사항을 준수한다면 사용할 수 있습니다.
· 네이버 AI 해커톤 2018에 참여해 개발한 알고리즘이라는 점을 Acknowledgement에 명시
· 데이터에 대한 구체적인 설명이나 예시를 들 수 없음
· 단, 데이터의 구체적 내용을 유추할 수 없는 범위에서 데이터 구조에 대한 설명이나 데이터 Summary 및 Descriptive Statistics를 보여주는 것은 가능

위 사항만 준수한다면 논문 작성하셔서 제출하는건 좋은 시도인 것 같습니다. :)
감사합니다.

**Comment by DaehunGwak** [comment]
@kobiso 감사합니다! 해당 사항 준수하여 작성해보도록 하겠습니다!
