### ISSUE TITLE
NSML Dataset을 불러오지 못합니다.

### ISSUE THREAD

**Issue by Ssojux2** [AiHackathon2018/AI-Vision#42]
TF Eager execution을 이용해서 작성중인데,

계속 데이터셋을 못 불러오길래, 코드문제인것같아서 계속 찾다가

결국 베이스라인을 돌려보니 데이터셋을 불러오지 못합니다.

처음 베스트라인을 테스트 했을때는 

```
_________________________________________________________________
dataset path /data/ir_ph1

4316 train samples
```

으로 뜨면서 잘불러왔는데, 중간에 제가 코드를 작성하면 계속 아래와 같이 나오더라구요

```
dataset path /data/ir_ph1

0 train samples
```

이렇게 나오면서 종료되길래 제 코드 문제인줄 삽질을 계속하다가

뭐가문제인지 도저히 모르겠어서

베이스라인 코드를 다시 돌려봤는데

```
_________________________________________________________________
dataset path /data/ir_ph1
 
0 train samples
```

이렇게 뜨면서 테스트 데이터를 전혀불러오지 못하네요. 혹시 이런경우 해결방법이 있을까요?

**Comment by Hackoperation** [comment]
안녕하세요. 

혹시 main.py가 있는 폴더에 img_list.pkl파일과 label_list.pkl파일이 있진않나요?

nsml상에 해당 파일도 같이 올라가서 문제가 발생한것같습니다. 해당파일을 지우고 다시 실행해주시면될것같습니다.

감사합니다.

**Comment by Ssojux2** [comment]
간단한 이슈였군요 ㅠㅠ 감사합니다 해결되었습니다.
