### ISSUE TITLE
nsml model ls & submit 에 문제가 있습니다.

### ISSUE THREAD

**Issue by Ssojux2** [AiHackathon2018/AI-Vision#54]
> $ nsml model ls [session]
> $ nsml submit [session] [checkpoint]

위 내용으로 명령어를 실행시

> ] Invalid request

만 나오면서 동작하지 않습니다.

> [teamname]/ir_ph1/[session number]

Session에 세션 번호를 입력했고 checkpoint는 어떻게 확인을하는건가요?

model ls가 동작을 안해서 확인이 어려운건가요?

**Comment by Hackoperation** [comment]
위와같이 Invalid request는 세션네임을 잘못입력하거나 권한 문제로 인해서 발생하는걸로 보입니다.

전체 스크린샷이나 터미널로그를 보여주시면 확인할수있을것같습니다.

감사합니다.

**Comment by Ssojux2** [comment]
팀명에 오타가 있었네요... 감사합니다.
