### ISSUE TITLE
login 할 때 다음과 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by LenKIM** [AiHackathon2018/AI-Vision#60]
```
INFO[2019/01/03 13:23:28.798] connecting to hack-cli.nsml.navercorp.com:18553
INFO[2019/01/03 13:23:43.800] could not get the update URL: rpc error: code = DeadlineExceeded desc = context deadline exceeded
FATA[2019/01/03 13:23:43.800] please check your network connectivity by using 'ping hack-cli.nsml.navercorp.com'
```
혹시 포트 문제일까요?

**Comment by nsml-admin** [comment]
@davinnovation 님. 
팀이름과 아이디를 다르게 설정하시도록 가이드렸는데, 동일하게 입력하서 문제가 있었습니다. 
현재, 임의의 팀이름을 부여하였습니다.  혹시, 팀 변경을 원하시면 dl_nsml_alpha@navercorp.com 로 변경 요청메일부탁드립니다.

**Comment by nsml-admin** [comment]
@LenKIM 님. 
안녕하세요. 방화벽 등의 이슈가 있는 것으로 보여집니다. 
windows 환경에서 정상 동작하고 있는 것은 확인되고 있습니다. 
​
ping 이 된다면, hack-cli.nsml.navercorp.com 18553 port로 connect이 연결되는지 확인이 되어야하는데요. 
아마도 port에 대한 방화벽이 동작중인 듯 합니다. ​
​
telnet 프로램이 설치된 다른 장비에서 아래 명령으로 connection이 정상적으로 이루어 지는지 확인하셔야하셔야할 것 같습니다. 
```
telnet hack-cli.nsml.navercorp.com 18553  
```
​
추가로, 웹 https://hack.nsml.navercorp.com 에서 login이 잘 된다면, ID는 잘 생성된 상태입니다. 
​
현시점의 CLI login 상태는 아래와 같습니다. ​
```
D:\book_dn\windows\nsml_client.windows.amd64.hack>nsml.exe login
INFO[2019/01/02 14:50:09.023] connecting to hack-cli.nsml.navercorp.com:18553
INFO[2019/01/02 14:50:10.075] there is no update
GitHub Username:
```

**Comment by LenKIM** [comment]
해당 이슈는 해결되어 close하겠습니다.
답변해주셔서 감사합니다.
