### ISSUE TITLE
[SOLVED] Error: Error occurred while loading model 

### ISSUE THREAD

**Issue by jaehyunnn** [AiHackathon2018/AI-Vision#67]
모델 inference를 진행 하기위해 submit을 할시 다음과 같은 에러가 발생합니다.

현재 코드는 pytorch로 재구현 하여 진행하고 있습니다.

    def save(dir_name):
        os.makedirs(dir_name, exist_ok=True)
        checkpoint_name = os.path.join(dir_name, 'model.pth')
        torch.save(model.state_dict(), checkpoint_name)

    def load(file_path):
        dir = file_path + '/model.pth'
        checkpoint = torch.load(dir, map_location=lambda storage, loc: storage)
        model.load_state_dict(checkpoint)

save, load 관련 method는 다음과 같이 구현을 하였는데 이부분에서 오류가 발생하는 것 같은데, nsml 내부적으로 inference하는 방식을 알수가 없어서 조언을 구하고자 올립니다.

**Comment by Hackoperation** [comment]
안녕하세요.

세션네임을 몰라서 자세한 답변을 못드리겠지만

save는 제대로 저장되는것같은데 load할때 의 문제가 생긴것같습니다. 

save할때 파일을 1개만 저장한다면, 로드할때 argument로 들어오는 file_path는 바로 해당 파일로 들어올것이고, `file_path` 자체를 `torch.load`에 argment로 넘겨주면 될것같습니다.

아래와 같이 수정 해보실래요? 

도큐먼트 페이지도 참고해보시기바랍니다. [참고](https://n-clair.github.io/vision-docs/_build/html/ko_KR/contents/nsml_library/nsml_bind.html#nsml-bind-load)

혹시 그래도 문제가 생긴다면 세션네임을 알려주시면 도움이될것같습니다.

감사합니다.
```python
def load(file_path):
    dir = file_path
    checkpoint = torch.load(dir, map_location=lambda storage, loc: storage)
    model.load_state_dict(checkpoint)
```
