### ISSUE TITLE
GPU 할당량 질문

### ISSUE THREAD

**Issue by Baekyeongmin** [AiHackathon2018/AI-Vision#71]
안녕하십니까? DGVision 팀입니다.

pytorch로 구현후에 학습을 진행중에 있는데 gpu할당에 대해 궁금한 점이 있습니다.

cli에서 nsml g 옵션 2까지는 제대로 동작하지만 3이상을 할당하게되면

Error: No machine available that meets ALL your request such as CPU, RAM, Disk, GPU or its driver version

위와 같은 에러가 발생합니다. resource에는 충분한 gpu가 있는걸로 보여지는데, 2개이상은 사용할 수 없는지 궁금합니다.

**Comment by nsml-admin** [comment]
안녕하세요. 해커톤에서는 1session에서 동시에 2개까지만 지원하고 있습니다. 
session은 여러개 실행가능합니다.
