### ISSUE TITLE
Pytorch bind_model에 load()에 대한 질문입니다.

### ISSUE THREAD

**Issue by wjy5446** [AiHackathon2018/AI-Vision#75]
현재 pytorch을 이용해서 bind_model을 작성하고 있습니다.

현재 제가 다음 아래와 같이 코드를 작성했지만, load()관련해서 오류가 발생합니다.
```
def bind_model(model):
    def save(dir_name):
        print(dir_name)
        os.makedirs(dir_name, exist_ok=True)
        torch.save(model.state_dict(), os.path.join(dir_name, 'model.pth'))
        print('model saved!')

    def load(dir_name):
        print(dir_name)
        model.load_state_dict(os.path.join(dir_name, "model.pth"))
        print('model loaded!')
```

각각 save와 load의 dir_name을 보면
save은 `/tmp/tmpslx92090`
load는 `/tmp/tmp07k9pqgr`
라고 나옵니다.

혹시 어디가 잘못되었는 지 궁금합니다.
감사합니다.

**Comment by Hackoperation** [comment]
https://github.com/AiHackathon2018/AI-Vision/issues/67 와 같은이슈인것같습니다.

`os.path.join`부분에서 `"model.pth"`를 제외하시면 될것같습니다.

감사합니다.
