### ISSUE TITLE
model 을 save 및 기타 데이터 저장 대한 질문입니다.

### ISSUE THREAD

**Issue by DevKiHyun** [AiHackathon2018/AI-Vision#77]
학습 중 또는 완료 후 save 함수로 저장되는 파일들은 남아 있게 되나요?
예를 들어 52 라는 세션에서 저장된 파일들이 새로운 53 세션에서 접근 가능한지 궁금합니다.

**Comment by Hackoperation** [comment]
학습 도중 또는 완료된 세션이든 `nsml.save()`로 전달된 argument에 저장된 파일들은 남아있지않습니다. (nsml 상의 개인 storage 서버가 있는데 그곳에 저장됩니다)

세션 52 에서 `nsml.save()`로 제대로 저장이 되었다면, 
세션 53 에서는 `nsml.bind(load=load)` 로 52에 저장된 모델을 불러오는 load함수를 바인딩후에,  `nsml.load(checkpoint, session='sessionName')`과 같이 불러올수있습니다.

 예제)
```python
def load(self):
    load_delivery = []

    # load_delivery의 빈 리스트를전달하면 nsml.load 함수가 실행된후 해당리스트는 모델로 채워지고 값을 가져올수있습니다.
    bind_load_model(load_delivery)
    nsml.load('0', session='nsml-team/ir_ph1_v2/52')

    network = load_delivery[0]


def bind_load_model(load_delivery):
    def nsml_load(dir_name):
        state = torch.load(dir_name)
        load_delivery.append(state)

    nsml.bind(load=nsml_load)
```

**Comment by DevKiHyun** [comment]
개인 storage 서버는 접근 가능한가요? 가능하다면 처리된 데이터를 읽고/쓰기가 가능한가요? docs에서 찾아보질 못한 것 같습니다.

**Comment by Hackoperation** [comment]
아쉽지만 개인storage 는 접근할수없습니다 ㅠ.ㅠ 
하지만 세션내에서 처리된 데이터를 쓴 파일(저장된 파일)은 다운받아올수있습니다.

**Comment by DevKiHyun** [comment]
아 처리된 데이터가 저장된 파일은 로컬로 다운을 받을 수 있단 얘기군요?

**Comment by DevKiHyun** [comment]
로컬로 다운 받을 수 있다는 얘기인가요?

**Comment by Hackoperation** [comment]
nsml.cache()기능을 이용하면될것같습니다. 

전처리 함수가 바뀔때마다 함수이름을 바꿔서 cache에 함수를 넘겨주면 새롭게 캐시파일을 생성합니다.

https://github.com/AiHackathon2018/AI-Vision/issues/73#issuecomment-451340795
