### ISSUE TITLE
팀명이 github에 이미 존재하는 username이면 안되나요?

### ISSUE THREAD

**Issue by tigersdennn** [AiHackathon2018/AI-Vision#8]
팀명을 적는 란에 "Github username은 5자리 이상, 대/소문자 영어 5~20자리, 특수문자는 “_” 만 가능합니다." 라고 쓰여있는것으로 보아, 팀명이 github 아이디로 발행되는것 같은데, 그렇다면 github에 이미 존재하는 아이디는 팀명으로 사용할 수 없는 것인가요?

**Comment by nsml-admin** [comment]
안녕하세요.

팀명이 github 아이디로 발행되는 것이 아니고,
nsml 플랫폼 내에 계정 ID와 팀 ID가 겹치지 않아야 합니다.

github에서 존재하는 ID를 팀명으로 사용 못한다가 아닌,
nsml 플랫폼 내에서 개인ID, 팀명 ID가 겹치지 않아야 합니다. 

만약 다른팀이랑 팀명이 겹치게 된다면 따로 변경요청 메일을 드릴 예정입니다.

감사합니다.
