### ISSUE TITLE
submit 코드 infer 변경 질문

### ISSUE THREAD

**Issue by DaehunGwak** [AiHackathon2018/AI-Vision#89]
안녕하세요. `24시간이모자라`팀의 곽대훈입니다.

혹시 `nsml submit` 명령을 하게 되면 nsml 측의 `bind_model` 의 `infer`를 실행하게 되나요?

`infer`를 손보아서 모델의 다른 부분 feature를 뽑게 해주고 싶은데 로컬로만 변경하면 안되는 것 같아 질문 드립니다. 감사합니다 👍

**Comment by comisputer** [comment]
저도 이부분 궁금합니다.

**Comment by DaehunGwak** [comment]
@comisputer 아 실험해보니 `nsml run`할 때 `main.py`를 같이 올린 시점의 `infer` 코드로 실행하게 됩니다!
