### ISSUE TITLE
opencv install 안되시는 분 계신가요?

### ISSUE THREAD

**Issue by ttagu99** [AiHackathon2018/AI-Vision#96]
[91mCould not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.5/site-packages/cv2/LICENSE.txt'
[0m
이런 메세지 뜨면서 안되는데요.
같은 현상 경험하셨거나 해결하신 분 있으시나요?

**Comment by ttagu99** [comment]
> 안녕하세요. 저는 cv2 importerror가 나는데, cv2를 설치하려고 하면 이미 설치되어있다고 뜹니다.
> 혹시 이와 같은 경우 해결해보셨나요?ㅠ

메인 질문에 답변 드렸습니다~ 확인해보세요~.

**Comment by jireh-father** [comment]
@ttagu99  안녕하세요.
저도 동일한 에러가 발생해서 조언을 구할 수 있을까요?
전 opencv만 설치하는데도 동일한 에러가 발생합니다.

#nsml: nsml/ml:cuda9.0-cudnn7-tf-1.11torch0.4keras2.2

from distutils.core import setup

setup(
    name='nsml vision hackathon',
    version='1.0',
    description='nsml vision hackathon',
    install_requires=[
        'opencv-python'
    ]
)
