### ISSUE TITLE
nsml fork 명령시 epochs이 정확히 입력되지 않는 것 같습니다.

### ISSUE THREAD

**Issue by Ssojux2** [AiHackathon2018/AI-Vision#98]
fork 명령어 중에서 

-a "--epochs=1000, --batch=128, --lr=1e-6, --iteration=99"

를 옵션으로 줬는데, 세션에 올라간것을 보니 --epochs가 1로 입력되고

allocated된 상태로 삭제도 되지 않습니다. 

문서도 좀 찾아봤지만, 이 내용은 없는 것 같습니다.

아직까지 사라지지도 않네요. 혹시 이거에 관련된 내용을 찾아볼수있을까요?

**Comment by Ssojux2** [comment]
allocated 된상태로 멈춰버려서 gpu 사용도 불가하네요;;

**Comment by Ssojux2** [comment]
세션은 해결 됐지만 옵션으로 에폭조정은 안되네요 ㅠㅠ

**Comment by rlatjcj** [comment]
argparse 주는 것처럼 comma 안붙히면 옵션 조정됩니다!

**Comment by doublejtoh** [comment]
저도 똑같은 문제 겪고있습니다.. fork시에 --epochs 가 제대로 parsing이 되지 않네요

**Comment by Hackoperation** [comment]
안녕하세요.
epochs는 nsml에서 reserved키워드 인데 옵션으로 줘서 문제인것같습니다. 현재 fork를 사용하면 무조건 1로 셋팅되는데요 epochs를 말고 다른 이름으로 변경해서 다시 테스트부탁드립니다.

불편을드려서 죄송합니다 해당부분은 곧 baseline에서도 수정하겠습니다.

감사합니다.

**Comment by Ssojux2** [comment]
알겠습니다. 감사합니다.
